### ISSUE TITLE
Problem querying old data with multiple retentions

### ISSUE THREAD

**Issue by fmacgregor** [graphite-project/whisper#166]
There was a question asked at [https://answers.launchpad.net/graphite/+question/285178](https://answers.launchpad.net/graphite/+question/285178) which I include a copy of the text from below. I have discovered that this is resolved by reverting the change made by @obfuscurity  in [https://github.com/graphite-project/whisper/commit/ccd0c89204f2266fa2fc20bad7e49739568086fa](https://github.com/graphite-project/whisper/commit/ccd0c89204f2266fa2fc20bad7e49739568086fa)

i.e. change 
```
  diff = untilTime - fromTime
  for archive in header['archives']:
    if archive['retention'] >= diff:
      break
```
back to
```
  diff = now - fromTime
  for archive in header['archives']:
    if archive['retention'] >= diff:
      break
```
Changing this back satisfies the requirement in [http://graphite.readthedocs.io/en/latest/whisper.html](http://graphite.readthedocs.io/en/latest/whisper.html) namely

> When data is retrieved (scoped by a time range), the first archive which can satisfy the entire time period is used. If the time period overlaps an archive boundary, the lower-resolution archive will be used. This allows for a simpler behavior while retrieving data as the data’s resolution is consistent through an entire returned series.

Here is a copy of the original question:

We've been running a grafana/graphite-api/carbon/whisper stack for a while now and it's working generally ok. However, I've noticed that if I drill into data in grafana, once I get to a certain level of detail, the chart is blank.

Here is some config. Our storage schema looks like this, store on a 10 sec interval for 7 days, then 1 minute for 2 years.

[Web_Prod]
priority = 90
pattern = ^Production.*.web.*.WebServer.*
retentions = 10s:7d,1m:2y

I can verify this in the whisper files themselves, like this: -

/usr/local/src/whisper/bin/whisper-dump.py /opt/graphite/storage/whisper/Production/Live/web/web2-vm/WebServer/Customer/HPS.wsp | less

Meta data:RETURN)
  aggregation method: average
  max retention: 63072000
  xFilesFactor: 0

Archive 0 info:
  offset: 40
  seconds per point: 10
  points: 60480
  retention: 604800
  size: 725760

Archive 1 info:
  offset: 725800
  seconds per point: 60
  points: 1051200
  retention: 63072000
  size: 12614400

I've noticed the problem only happens, when querying data older than 7 days i..e after it's been averaged to a 60 second interval. If I pick a time period older than 7 days, across a three minute interval, and look directly inside the whisper file, it all looks good: -

/usr/local/src/whisper/bin/whisper-fetch.py --from 1454230700 --until 1454230880 /opt/graphite/storage/whisper/Production/Live/web/web2-vm/WebServer/Customer/HPS.wsp

1454230740 8.000000
1454230800 8.700000
1454230860 8.233333

However, if I query through graphite-api, it returns a 10 second interval (the wrong retention period, because I'm querying older than 7 days), and all items (even the ones that match the timestamps above) are null.

http://www.dashboard.com/render?target=Production.Live.web.web2-vm.WebServer.Customer.HPS&from=1454230700&until=1454230880&format=json&maxDataPoints=1000

[{"target": "Production.Live.web.571854-web2-vm.WebServer.Customer.HPS", "datapoints": [[null, 1454230710], [null, 1454230720], [null, 1454230730], [null, 1454230740], [null, 1454230750], [null, 1454230760], [null, 1454230770], [null, 1454230780], [null, 1454230790], [null, 1454230800], [null, 1454230810], [null, 1454230820], [null, 1454230830], [null, 1454230840], [null, 1454230850], [null, 1454230860], [null, 1454230870], [null, 1454230880]]}]

If I go for a wider time span, I start to get data back, but some are null and some are populated.

**Comment by deniszh** [comment]
@fmacgregor - does revert this change fixes your issue?
It's reverted because it was breaking Graphite horribly IIRC.

**Comment by toopa2002** [comment]
I also found same issue, but revert the change isn't help.

**Comment by deniszh** [comment]
@toopa2002 - change was reverted long time ago. Which version of whisper/graphite do you use?

**Comment by toopa2002** [comment]
They are 0.9.12.  I also try to patch Whisper to 0.9.15 but it not help.

**Comment by deniszh** [comment]
Then your problem doesn't connect with the change above, it's something else.
Could you please describe what your problem is?
Because TBH I do not understand what @fmacgregor problems either...

**Comment by toopa2002** [comment]
- My metric has following setting.
[tsd_aapp]
pattern = ^stats.*\.tim-tsd-aapp.*
retentions = 10s:28d, 60s:180d, 1h:1y, 1d:5y

- The problem when I query data older than 28 days using graphite api or whisper-fetch, the result are "None" as below. The result return collectly if query less than 28 days. My whisper file is -> https://drive.google.com/open?id=0B7iSHsHBocNQLUVLbElTYkhvV3c

whisper-fetch.py /opt/graphite/whisper/stats/dc/env-dc-phy/tim-tsd-aapp/c5551234cccc/os/memory/ram_bufsz.wsp --from=1470030582 --until=1472550309 |more
1470030600	None
1470030660	None
1470030720	None
1470030780	None
1470030840	None
1470030900	None
1470030960	None
1470031020	None
....

**Comment by deniszh** [comment]
Yes, that's could happen with wrong retention interval and aggregation schema.
What's your aggregation schema ([storage-aggregation.conf](http://graphite.readthedocs.io/en/latest/config-carbon.html#storage-aggregation-conf))?
Also, did you really send data every 10s or you sending data e.g. every minute and have gaps, e.g.
```
1470030600 1.0
1470030610 None
1470030620 None
1470030630 None
1470030640 None
1470030650 None
1470030660 1.0
1470030670 None
...
```

**Comment by toopa2002** [comment]
The metric was sending every minute. Does the mis-match between sending interval and retention period  cause the issue?  My aggregation schema as below.
# Time Series - ETS IntradayWS - LAST
[tsd_aapp_last]
pattern = ^stats.*\.tim-tsd-aapp.*\.*last
aggregationMethod = last
# Time Series - ETS IntradayWS - MAX
[tsd_aapp_max]
pattern = ^stats.*\.tim-tsd-aapp.*\.*max
aggregationMethod = max
[default_average]
pattern = .*
xFilesFactor = 0.5
aggregationMethod = max

**Comment by deniszh** [comment]
Exactly. Maybe we need to include an explanation in the docs.
Look how Whisper works - it stores data in archives. Every archive has a number of points and retention. When you saying `10s:28d, 60s:180d, 1h:1y, 1d:5y` for every metric Graphite will create 4 archives. In your case 1st archive will contain with `(28*24*60*60)/10` = 241920 points and it expects that data will come every 10 seconds. The second archive will have `(180*24*60*60)/60` = 259200 points and will expect every point for 60 seconds.
But how data propagates to different archives? There's storage aggregation mechanism! It has 2 parameters - `aggregationMethod` and `xFilesFactor`.
Again, in your case 
```
pattern = .*
xFilesFactor = 0.5
aggregationMethod = max
```
What does it mean? It means that Graphite will aggregate data using max value, and will trust data only if 50% of it is present.
So, if you sending data every 10 seconds you will have it 1st archive e.g.
```
1470030600 1
1470030610 2
1470030620 3
1470030630 100
1470030640 0
1470030650 0
```
Then aggregation mechanism takes aggregationMethod ('max') and put result of 6 points from archive 1 to archive 2. max(1,2,3,100,0,0) = 100.
So, in the second archive we have
```
1470030660 100
```
Next batch:
```
1470030660 7
1470030670 8
1470030680 9
1470030690 1
1470030700 8
1470030710 17
```
will give you in 2nd archive = max(7,8,9,1,8,17) = 17. So, 2nd archive now has
```
1470030660 100
1470030720 17
```
etc - it works in a similar way for 3rd and 4th archive.

But what happens when you have retention = 10s but sending data every minute?
```
1470030600 1
1470030610 None
1470030620 None
1470030630 None
1470030640 None
1470030650 None
1470030660 7
1470030670 None
1470030680 None
1470030690 None
1470030700 None
1470030710 None
```
Aggregation checks your `xFilesFactor` - it's 0.5 - that means 50%. But you have only 1 point and 5 Nones! it's 15%, and 15% < 50%.
So graphite decides that it didn't have valid data for aggregation and puts None in 2nd archive -
```
1470030660 None
1470030720 None
```

So, the proper way for fixing that - you need to make your lowest retention to match your metrics rate. If all of your metrics coming every minute - you need to have the `60s:28d` retention and not `10s:28d`.
If you have some metrics coming every 10 seconds and other metrics coming every 60 seconds - you need to properly configure your storage aggregation to decrease xFilesFactor for these metrics to 0.1 or even 0.0.

Unfortunately, both `xFilesFactor` and retention are included in whisper file structure during creation - so, you need to delete old wsp files after fixing your parameters (and obviously loose your data). Or you can try [whisper-auto-resize.py](https://github.com/graphite-project/whisper/blob/master/contrib/whisper-auto-resize.py) script to resize your existing metrics.

**Comment by toopa2002** [comment]
@deniszh Thank you very much.

**Comment by bakerkj** [comment]
I'd like to request that someone add this helpful discussion about xFilesFactor to the whipser database docs in http://graphite.readthedocs.io/en/latest/whisper.html.  Maybe this is something you @deniszh could do?
 
Thanks!

**Comment by deniszh** [comment]
Hello @bakerkj,
Anyone can do that - documentation is on Github too - https://github.com/graphite-project/graphite-web/blob/master/docs/whisper.rst
I'm not a native English speaker, so, usually, I'm refraining myself from touching the documentation if it's not absolutely necessary.
