### ISSUE TITLE
whisper-resize.py corrupts data in multi-archive metric

### ISSUE THREAD

**Issue by azhiltsov** [graphite-project/whisper#249]
During resizing on the file with the next whisper layout:
```
xFilesFactor: 0.0
aggregationMethod: sum 
1:172800 60:40320 3600:17520
```
to layout
```
xFilesFactor: 0.0
aggregationMethod: sum
1:172800 60:41760 3600:17520
```
we observe the data corruption. 

24 hours
![24_hours](https://user-images.githubusercontent.com/8709761/38381387-ec1a2aa0-3906-11e8-9ece-fc7dc7bb5f1f.png)
72 hours
![72_hours](https://user-images.githubusercontent.com/8709761/38381396-f0def32c-3906-11e8-989c-11e5b50593aa.png)
52 days
![52_days](https://user-images.githubusercontent.com/8709761/38381399-f48eb796-3906-11e8-851e-8859811c3fc4.png)

It seems that it is doing cross-archive fill during resize and aggregates the data with "sum" where it actually not needed. Details follows.
```
$ mkdir virt
$ virtualenv ./virt/whisper
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/azhiltsov/virt/whisper/bin/python2
Also creating executable in /home/azhiltsov/virt/whisper/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
$ cd ./virt/whisper/bin/
$ source activate
$ pip install whisper
Collecting whisper
  Downloading whisper-1.1.3.tar.gz
Collecting six (from whisper)
  Downloading six-1.11.0-py2.py3-none-any.whl
Building wheels for collected packages: whisper
  Running setup.py bdist_wheel for whisper ... done
  Stored in directory: /home/xxx/.cache/pip/wheels/8c/41/a9/a30beeda8b107e49d35347f096002f72c843a4ebeb33319029
Successfully built whisper
Installing collected packages: six, whisper
Successfully installed six-1.11.0 whisper-1.1.3
$ ./whisper-resize.py stat.wsp 1:172800 60:41760 3600:1752

$ ./whisper-info.py stat.wsp
maxRetention: 63072000
xFilesFactor: 0.0
aggregationMethod: sum
fileSize: 2785012

Archive 0
retention: 172800
secondsPerPoint: 1
points: 172800
size: 2073600
offset: 52

Archive 1
retention: 2505600
secondsPerPoint: 60
points: 41760
size: 501120
offset: 2073652

Archive 2
retention: 63072000
secondsPerPoint: 3600
points: 17520
size: 210240
offset: 2574772

$ ./whisper-info.py stat.wsp.bak 
maxRetention: 63072000
xFilesFactor: 0.0
aggregationMethod: sum
fileSize: 2767732

Archive 0
retention: 172800
secondsPerPoint: 1
points: 172800
size: 2073600
offset: 52

Archive 1
retention: 2419200
secondsPerPoint: 60
points: 40320
size: 483840
offset: 2073652

Archive 2
retention: 63072000
secondsPerPoint: 3600
points: 17520
size: 210240
offset: 2557492
```

[whisper_files.zip](https://github.com/graphite-project/whisper/files/1881061/whisper_files.zip)

**Comment by deniszh** [comment]
Hi @azhiltsov,
OK, I need to dig into this, but on a first glance you have a bad retentions configured, maybe that's the case. Please see 
https://graphite.readthedocs.io/en/latest/whisper.html#archives-retention-and-precision
"To support accurate aggregation from higher to lower resolution archives, the precision of a longer retention archive must be divisible by precision of next lower retention archive. For example, an archive with 1 data point every 60 seconds can have a lower-resolution archive following it with a resolution of 1 data point every 300 seconds because 60 cleanly divides 300. In contrast, a 180 second precision (3 minutes) could not be followed by a 600 second precision (10 minutes) because the ratio of points to be propagated from the first archive to the next would be 3 1/3 and Whisper will not do partial point interpolation."

**Comment by azhiltsov** [comment]
I am not quite sure about your statement. 
Precisions was 1,60,3600 seconds per point before and after the resize.
The resize was targeting only the second archive expantion:
172800,40320,17520 -> 172800,41760,17520

**Comment by deniszh** [comment]
@azhiltsov 
Ah, disregard that, I misread the whole thing. 🤦‍♂️ 
But I have another issue - can't reproduce on fresh whisper / graphite on python 2.7.
```
[dzhdanov:~/Downloads/graphie/whisper/test] $ whisper-info.py 2.wsp
maxRetention: 63072000
xFilesFactor: 0.0
aggregationMethod: sum
fileSize: 2767732

Archive 0
retention: 172800
secondsPerPoint: 1
points: 172800
size: 2073600
offset: 52

Archive 1
retention: 2419200
secondsPerPoint: 60
points: 40320
size: 483840
offset: 2073652

Archive 2
retention: 63072000
secondsPerPoint: 3600
points: 17520
size: 210240
offset: 2557492

[dzhdanov:~/Downloads/graphie/whisper/test] $ whisper-resize.py 2.wsp 1:172800 60:41760 3600:1752
Retrieving all data from the archives
Creating new whisper database: 2.wsp.tmp
Created: 2.wsp.tmp (2595796 bytes)
Migrating data without aggregation...
Renaming old database to: 2.wsp.bak
Renaming new database to: 2.wsp
[dzhdanov:~/Downloads/graphie/whisper/test] $ whisper-info.py 2.wsp
maxRetention: 6307200
xFilesFactor: 0.0
aggregationMethod: sum
fileSize: 2595796

Archive 0
retention: 172800
secondsPerPoint: 1
points: 172800
size: 2073600
offset: 52

Archive 1
retention: 2505600
secondsPerPoint: 60
points: 41760
size: 501120
offset: 2073652

Archive 2
retention: 6307200
secondsPerPoint: 3600
points: 1752
size: 21024
offset: 2574772

[dzhdanov:~/Downloads/graphie/whisper/test] $ mv 2.wsp.bak 2_orig.wsp
```

24 hours:
http://localhost/render/?width=825&height=483&target=test.2&target=test.2_orig&from=00%3A00_20180403&until=23%3A59_20180404
<img width="844" alt="screen shot 2018-04-08 at 21 11 35" src="https://user-images.githubusercontent.com/1227222/38471485-f38a2908-3b71-11e8-9927-260c2f60402c.png">


72 hours:
http://localhost/render/?width=825&height=483&target=test.2&target=test.2_orig&from=00%3A00_20180401&until=23%3A59_20180404
<img width="859" alt="screen shot 2018-04-08 at 21 15 06" src="https://user-images.githubusercontent.com/1227222/38471493-f97d15e6-3b71-11e8-8bf1-9880ed91f26e.png">


52 days:
http://localhost/render/?width=825&height=483&target=test.2&target=test.2_orig&from=00%3A00_20180211&until=23%3A59_20180404
<img width="843" alt="screen shot 2018-04-08 at 21 14 27" src="https://user-images.githubusercontent.com/1227222/38471495-ff3cd124-3b71-11e8-860e-7e09a8b1fb0f.png">

You can try yourself, using latest Graphite in docker, e.g.
```docker run \
 --restart=always\
 -p 80:80\
 -p 2003-2004:2003-2004\
 -p 2023-2024:2023-2024\
 -p 8125:8125/udp\
 -p 8126:8126 \
 -v /Users/dzhdanov/Downloads/graphie:/opt/graphite/storage \
 graphiteapp/graphite-statsd```

**Comment by deniszh** [comment]
Ah, I reproduced it with `whisper-resize.py --aggregate 3.wsp 1:172800 60:41760 3600:1752`
<img width="844" alt="screen shot 2018-04-08 at 21 32 46" src="https://user-images.githubusercontent.com/1227222/38471657-7a5de094-3b74-11e8-89a9-7eebfc6ebd2a.png">

**Comment by deniszh** [comment]
I tried fix from https://github.com/graphite-project/whisper/pull/177 - result looks better:
http://localhost/render/?width=825&height=483&target=test.3&target=test.3_orig&from=00%3A00_20180401&until=23%3A59_20180404
<img width="852" alt="screen shot 2018-04-08 at 21 40 01" src="https://user-images.githubusercontent.com/1227222/38471725-70f0a298-3b75-11e8-8e57-a8504d1d9835.png">
but conversion took ages, probably because of https://github.com/nazco/whisper/blob/f6fc3a0067ae1c368b3b08facaca0d4e8f663a36/bin/whisper-resize.py#L126
Also it created huge spike
http://localhost/render/?width=825&height=483&target=test.3&target=test.3_orig&from=00%3A00_20180101&until=23%3A59_20180404
<img width="858" alt="screen shot 2018-04-08 at 21 40 52" src="https://user-images.githubusercontent.com/1227222/38471729-9064b772-3b75-11e8-96f4-6a9e50be7b20.png">
