### ISSUE TITLE
[BUG] Graphite render API is giving time out issue if metrics key is more wild chard(*) letters

### ISSUE THREAD

**Issue by panditb** [graphite-project/whisper#297]
Hello Team,

 I have below metrics key :
`metrics.$hostname.api.agent.message.$apiName.$apiOperation.$customer.$apiKey.success.$statusCode.count`

API level: 
`curl -X GET "http://graphite-web:2006/render?target=sum(metrics.*.api.agent.message.*.*.*.*.success.200.count)&format=json&noNullPoints=true&from=20200501&until=23:59_20200531"`

**This CURL is giving me time out issue that** 
 
`curl -X GET "http://graphite-server-web:2006/render?target=sum(metrics.*.api.agent.message.UserAdminAPI.*.*.*.failure.200.count)&format=json&noNullPoints=true&from=20200501&until=23:59_20200531"`

**This CURL is giving me data since i have replcaed one of the * to the proper key name "UserAdminAPI"**

is there any limit to fetch the datapoints records ,
 can you please let us know is there any issue if more datapoints records then its failing? 

Graphite version  : 1.1.2

**Comment by deniszh** [comment]
We have `FIND_TIMEOUT` and `FETCH_TIMEOUT` (3 seconds by default) and `CARBONLINK_TIMEOUT` (1 second) - all of them are in local_settings.py -  see https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/local_settings.py.example

**Comment by bikashkumars** [comment]
@deniszh i am also working with @panditb on this issue. I wanted to clarify few things.

If there are too many records (data points) that we are fetching using render API. Because of that we are getting timeout. In that case, What is the best way forward for this solution ?

Scenario:
1. We are the reader here (we don't write data to graphite) rather we read data using render API
2. Is there any ways to limit the data by using render API so that timeout will not happen

**Comment by deniszh** [comment]
1. Try to increase timeouts above, also generic timeouts for your python execution (it really depends on your webserver (nginx or apache) and way of running graphite-web (wsgi/uwsgi/gunicorn etc)).
2. No, there's no such way. Also, not really getting what should happened if you limit such data - you will get e.g. 403 error instead of 500 - not that big difference, i think.

**Comment by piotr1212** [comment]
maybe this will be usefull for you: https://graphite.readthedocs.io/en/latest/render_api.html#maxdatapoints
