### ISSUE TITLE
whisper-info.py human-readable time information 

### ISSUE THREAD

**Issue by cdeil** [graphite-project/whisper#302]
I've been given some Whisper files and am learning to work with them for the first time.

Would it be possible to add an option to whisper-info.py so that the start and stop datetime is shown in a human-readable way?

Also: Looking at the docs it's not obvious to me what the offset is. 

Maybe this could be mentioned [here](https://graphite.readthedocs.io/en/latest/whisper.html) or in the README?

```
% whisper-info.py data/raw/sensors/00OA826.wsp       
aggregationMethod: average
maxRetention: 315363600
xFilesFactor: 0.5
fileSize: 82785664

Archive 0
offset: 52
secondsPerPoint: 10
points: 1555200
retention: 15552000
size: 18662400

Archive 1
offset: 18662452
secondsPerPoint: 60
points: 5256000
retention: 315360000
size: 63072000

Archive 2
offset: 81734452
secondsPerPoint: 3600
points: 87601
retention: 315363600
size: 1051212
```

**Comment by piotr1212** [comment]
whisper-info just dumps the header, you'd have to scan the whole file to find start/end dates. And it is more complex than just a linear scan select min/max timestamp because of the ringbuffer/round robin, old datapoints do not get cleaned up, only overwritten if a newer datapoint happens to need that position.

offset is the location where the data for this archive starts.
